:auto USING PERIODIC COMMIT 500 LOAD CSV WITH HEADERS FROM 'https://raw.githubusercontent.com/oudrea/publicdata/main/cvfiles/P0%20-%20Military%20Aircrafts-rel.csv' AS line 
         MATCH (nsrc:Entity { global_identifier: line.source_global_identifier }) WITH nsrc, line MATCH (ndest:Entity { global_identifier: line.destination_global_identifier }) WITH nsrc, ndest, line, apoc.convert.fromJsonMap(line.rel_properties) as ro CALL apoc.merge.relationship.eager(nsrc, line.rel_type, {}, ro, ndest, ro) YIELD rel RETURN rel;


:auto USING PERIODIC COMMIT 500 LOAD CSV WITH HEADERS FROM 'https://raw.githubusercontent.com/oudrea/publicdata/main/cvfiles/P0%20-%20Military%20Aircrafts-base.csv' AS line
     MERGE (n:Entity {global_identifier: line.global_identifier}) 
     ON CREATE SET n.name = line.name, n.label = line.label, n.types= line.types, n.name_variants= line.name_variants, n.caption= line.caption, n.wikipedia_url= line.wikipedia_url, n.wikidata_id= line.wikidata_id, n.dbpedia_id= line.dbpedia_id, n.data_source= line.data_source, n.source_identifier= line.source_identifier, n.global_identifier= line.global_identifier, n.description= line.description, n.key_phrases= line.key_phrases, n.handles= line.handles, n.websites= line.websites, n.hashtags= line.hashtags, n.emails= line.emails, n.name= line.Name, n.high_level_category= line.`High level category`, n.sub_categories= line.`Sub-categories`, n.manufacturer_country= line.`Manufacturer Country`, n.quantity= line.Quantity, n.variant= line.Variant, n.operating_country= line.`Operating Country`, n.operating_organization= line.`Operating Organization`, n.logo= line.logo, n.image= line.image, n.sources = [], n.source_ids = [] 
     ON MATCH SET n.name=line.name, n.label= line.label, n.types= line.types, n.name_variants= line.name_variants, n.caption= line.caption, n.wikipedia_url= line.wikipedia_url, n.wikidata_id= line.wikidata_id, n.dbpedia_id= line.dbpedia_id, n.description= line.description, n.key_phrases= line.key_phrases, n.handles= line.handles, n.websites= line.websites, n.hashtags= line.hashtags, n.emails= line.emails, n.name= line.Name, n.high_level_category= line.`High level category`, n.sub_categories= line.`Sub-categories`, n.manufacturer_country= line.`Manufacturer Country`, n.quantity= line.Quantity, n.variant= line.Variant, n.operating_country= line.`Operating Country`, n.operating_organization= line.`Operating Organization`, n.logo= line.logo, n.image= line.image
     RETURN n;
    